-- 2 - CRIACAO DE TABLEAS

CREATE DATABASE `VIRTUAL`;
USE `VIRTUAL`;

create table CADASTRO_FUNCIONARIO (
    CODFUN INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    DEPTO CHAR( 2),
    FUNCAO CHAR(20),
    SALARIO DECIMAL(10, 2)
);


-- 3 - INSERCAO DE REGISTROS

INSERT INTO CADASTRO_FUNCIONARIO (CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES (12, 'CARLOS ALBERTO', '3', 'VENDEDOR', 1530.00);


INSERT INTO CADASTRO_FUNCIONARIO (CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES (15, "MARCOS HENRIQUE", "2", "GERENTE", 1985.75);


INSERT INTO CADASTRO_FUNCIONARIO (CODFUN, NOME, DEPTO, FUNCAO, SALARIO)
VALUES (7, "APARECIDA SILVA", "3", "SECRETARIA", 1200.50);


INSERT INTO CADASTRO_FUNCIONARIO (CODFUN, NOME, DEPTO, SALARIO)
VALUES (44, "JACIBA DA SILVA", "3", 1500.00);

INSERT INTO CADASTRO_FUNCIONARIO
VALUES (2, 'WILSON DE MACEDO', '3', 'PROGRAMADOR', 1050.00);


INSERT INTO CADASTRO_FUNCIONARIO
VALUES (5, 'AUGUSTO SOUZA', '3', 'PROGRAMADOR', 1050.00);


-- 4 - CONSULTA DE REGISTROS


-- funcionários cadastrados
SELECT * FROM CADASTRO_FUNCIONARIO;

-- nome e a função
SELECT NOME, FUNCAO FROM CADASTRO_FUNCIONARIO;


-- quem trabalha em um departamento
SELECT NOME, CODFUN FROM CADASTRO_FUNCIONARIO
WHERE DEPTO = "3";

-- mudar a ordem da consulta, ascendente
SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO
ORDER BY NOME;



-- mudar a ordem da consulta, decrescente
SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO
ORDER BY NOME DESC;

SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO
ORDER BY NOME DESC;


-- de departamento menor para maior
SELECT DEPTO, NOME FROM CADASTRO_FUNCIONARIO
ORDER BY DEPTO, NOME DESC;

-- todos os funcionarios do departamento 3
SELECT NOME FROM CADASTRO_FUNCIONARIO
WHERE DEPTO = "3"
ORDER BY NOME;


-- 5 - ALTERACAO DE REGISTROS

SELECT * FROM CADASTRO_FUNCIONARIO WHERE CODFUN = 7;
UPDATE CADASTRO_FUNCIONARIO SET SALARIO = 2300.56 WHERE CODFUN = 7;


SELECT * FROM CADASTRO_FUNCIONARIO WHERE CODFUN = 7;
SELECT * FROM CADASTRO_FUNCIONARIO WHERE NOME = 'ANA BASTOS';

-- desativar safe mode em edit>preferences>sql editor>(Disable)safe updates
UPDATE CADASTRO_FUNCIONARIO SET DEPTO = '3' WHERE NOME = 'ANA BASTOS';
SELECT * FROM CADASTRO_FUNCIONARIO WHERE NOME = 'ANA BASTOS';


SELECT * FROM CADASTRO_FUNCIONARIO WHERE NOME = 'ANA BASTOS';
-- reajuste de 10%
SELECT * FROM CADASTRO_FUNCIONARIO;
UPDATE CADASTRO_FUNCIONARIO SET SALARIO = SALARIO * 1.10;

SELECT * FROM CADASTRO_FUNCIONARIO;


-- 6 - EXCLUSAO DE REGISTROS

SELECT * FROM CADASTRO_FUNCIONARIO;

SELECT DISTINCT DEPTO FROM CADASTRO_FUNCIONARIO;

DELETE FROM CADASTRO_FUNCIONARIO WHERE DEPTO = '2';

SELECT * FROM CADASTRO_FUNCIONARIO;

SELECT DISTINCT DEPTO FROM CADASTRO_FUNCIONARIO;

DELETE FROM CADASTRO_FUNCIONARIO WHERE NOME = 'MARCELO SOUZA';

SELECT * FROM CADASTRO_FUNCIONARIO;



-- 7 - ALTERACAO DA ESTRUTURA DA TABELA

SELECT * FROM CADASTRO_FUNCIONARIO;

ALTER TABLE CADASTRO_FUNCIONARIO ADD ADMISSAO DATE;

SELECT * FROM CADASTRO_FUNCIONARIO;

UPDATE CADASTRO_FUNCIONARIO SET ADMISSAO = '2006-01-15' WHERE CODFUN = 2;

UPDATE CADASTRO_FUNCIONARIO SET ADMISSAO = '1999-10-21' WHERE CODFUN = 3;

UPDATE CADASTRO_FUNCIONARIO SET ADMISSAO = '2004-10-21' WHERE CODFUN = 4;

UPDATE CADASTRO_FUNCIONARIO SET ADMISSAO = '2006-04-26' WHERE CODFUN = 5;

UPDATE CADASTRO_FUNCIONARIO SET ADMISSAO = '1980-05-10' WHERE CODFUN = 7;

UPDATE CADASTRO_FUNCIONARIO SET ADMISSAO = '1999-12-15' WHERE CODFUN = 9;

UPDATE CADASTRO_FUNCIONARIO SET ADMISSAO = '2000-12-21' WHERE CODFUN = 12;

UPDATE CADASTRO_FUNCIONARIO SET ADMISSAO = '2000-10-21' WHERE CODFUN = 25;

SELECT * FROM CADASTRO_FUNCIONARIO; 



SELECT NOME, ADMISSAO FROM CADASTRO_FUNCIONARIO
WHERE MONTH(ADMISSAO) = 12;

SELECT NOME, ADMISSAO FROM CADASTRO_FUNCIONARIO
WHERE ADMISSAO >= '2000-01-01';



INSERT INTO CADASTRO_FUNCIONARIO VALUES (15, 'MARCOS HENRIQUE', '2', 'GERENTE', 2184.33, '2006-05-25');

INSERT INTO CADASTRO_FUNCIONARIO VALUES (20, 'AUDREY TOLEDO', '2', 'SUPERVISORA', 1700.00, '2006-07-05');

INSERT INTO CADASTRO_FUNCIONARIO VALUES (22, 'SANDRA MANZANO', '2','ANALISTA', 2000.00, '2006-07-01');

INSERT INTO CADASTRO_FUNCIONARIO VALUES (24, 'MARCIO CANUTO', '2', 'PROGRAMADOR', 1200.00, '2006-07-10');

SELECT * FROM CADASTRO_FUNCIONARIO;
----------------------------------------------------


-- CONSULTA COM OPERADORES

-- 1 - OPERADORES ARITIMETICOS

SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO;
SELECT NOME, SALARIO + 100 FROM CADASTRO_FUNCIONARIO;
SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO;
SELECT NOME, SALARIO * 1.20 FROM CADASTRO_FUNCIONARIO;
SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO;

-- 2 - OPERADORES DE COMPARACAO OU RELACIONAIS

SELECT * FROM CADASTRO_FUNCIONARIO WHERE DEPTO = '5';
SELECT * FROM CADASTRO_FUNCIONARIO WHERE FUNCAO = 'VENDEDOR';
SELECT * FROM CADASTRO_FUNCIONARIO WHERE SALARIO <= 1700;
SELECT * FROM CADASTRO_FUNCIONARIO WHERE SALARIO > 1700 + 50;
SELECT * FROM CADASTRO_FUNCIONARIO WHERE SALARIO > (1700 + 50);

-- 3 - OPERADORES LOGICOS

SELECT * FROM CADASTRO_FUNCIONARIO
WHERE (DEPTO = '3') AND (FUNCAO = 'PROGRAMADOR');

SELECT * FROM CADASTRO_FUNCIONARIO
WHERE (DEPTO = '3') OR (DEPTO = '5');

SELECT * FROM CADASTRO_FUNCIONARIO
WHERE NOT (FUNCAO = 'VENDEDOR');

SELECT * FROM CADASTRO_FUNCIONARIO
WHERE (DEPTO = '5') XOR (FUNCAO = 'PROGRAMADOR');

-- 4 - OPERADORES ADICIONAIS


ALTER TABLE CADASTRO_FUNCIONARIO ADD FILHOS SMALLINT;


ALTER TABLE CADASTRO_FUNCIONARIO ADD MORTO SMALLINT;

SELECT NOME, FILHOS FROM CADASTRO_FUNCIONARIO;

SELECT CODFUN, NOME, FILHOS FROM CADASTRO_FUNCIONARIO
WHERE FILHOS IS NULL;

SELECT CODFUN, NOME, FILHOS FROM CADASTRO_FUNCIONARIO
WHERE NOT FILHOS IS NULL;

SELECT CODFUN, NOME, FILHOS FROM CADASTRO_FUNCIONARIO
WHERE FILHOS IS NOT NULL;

SELECT CODFUN, NOME, FILHOS FROM CADASTRO_FUNCIONARIO
WHERE NOT (FILHOS IS NULL);



UPDATE CADASTRO_FUNCIONARIO SET FILHOS = 1 WHERE CODFUN = 2;
UPDATE CADASTRO_FUNCIONARIO SET FILHOS = 3 WHERE CODFUN = 3;
UPDATE CADASTRO_FUNCIONARIO SET FILHOS = 2 WHERE CODFUN = 5;
UPDATE CADASTRO_FUNCIONARIO SET FILHOS = 1 WHERE CODFUN = 9;
UPDATE CADASTRO_FUNCIONARIO SET FILHOS = 4 WHERE CODFUN = 20;
UPDATE CADASTRO_FUNCIONARIO SET FILHOS = 3 WHERE CODFUN = 25;

SELECT CODFUN, NOME, FILHOS FROM CADASTRO_FUNCIONARIO;

SELECT CODFUN, NOME, FILHOS FROM CADASTRO_FUNCIONARIO
WHERE FILHOS IS NULL;

SELECT CODFUN, NOME, FILHOS FROM CADASTRO_FUNCIONARIO
WHERE NOT (FILHOS IS NULL);

SELECT * FROM CADASTRO_FUNCIONARIO
WHERE SALARIO BETWEEN 1700 AND 2000;

SELECT * FROM CADASTRO_FUNCIONARIO
WHERE SALARIO NOT BETWEEN 1700 AND 2000;

SELECT * FROM CADASTRO_FUNCIONARIO
WHERE DEPTO IN ('2', '3');

SELECT * FROM CADASTRO_FUNCIONARIO
WHERE DEPTO NOT IN ('2', '3');


SELECT * FROM CADASTRO_FUNCIONARIO WHERE NOME LIKE 'A%';
SELECT * FROM CADASTRO_FUNCIONARIO WHERE NOME LIKE '_A%';
SELECT * FROM CADASTRO_FUNCIONARIO WHERE NOME LIKE '%AN%';
SELECT * FROM CADASTRO_FUNCIONARIO WHERE SALARIO LIKE '%6';
SELECT * FROM CADASTRO_FUNCIONARIO WHERE SALARIO LIKE '_5%2';
SELECT * FROM CADASTRO_FUNCIONARIO WHERE NOME NOT LIKE '%AN%';


SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO WHERE SALARIO LIKE  "11%";
SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO WHERE SALARIO LIKE  "%8%";
SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO WHERE SALARIO LIKE  "_0%";
SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO WHERE SALARIO LIKE  "1_%_%";
SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO WHERE SALARIO LIKE  "%6";
SELECT NOME, SALARIO FROM CADASTRO_FUNCIONARIO WHERE SALARIO LIKE  "_1%6";

SELECT * FROM CADASTRO_FUNCIONARIO;